### ISSUE TITLE
Add Meetup integration

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#6]

**Comment by Ditofry** [comment]
For now I'm just going to show the next meetup and establish the API key and code for connecting to meetup.com

**Comment by Ditofry** [comment]
Just a thought for our next meetup:
I'm using the CFAPI for integrating meetup.com data (which was very painless. thanks CFAPI :+1: )  and I was wondering if people would be interested developing a little bit more infrastructure for templating the data that comes out of CFAPI, especially since this issue,  #1,  #4 and possibly future issues will be using data from the API.  I was thinking of using handlebars, but we could use whatever.

Like I said, we can talk about it the next time we meet, but I would be happy to make templates available via handlebars so that developers don't have to wrangle their own JSON for working with the API, and that way designers can just look at a simple templating guide to add/change UI in a way similar to the following:
```javascript
  // js/templates/meetup_section.hbs
  {{#each upcomingEvent}}
   <div class="meetup-event">
      <h3>{{title}}</h3>
      <p>{{description}}</p>
  </div>
  {{/each}}
```

It could easily be a part of the same PR to expose JSON as .hbs data for Projects, other brigades, or any other API data.

The drawback is complexity of the dev environment, of course.  We would need to add steps for compiling or watching the templates as well as instructions for installing the right tools (grunt or gulp or something like that).  For now I'll just integrate the Meetup in pure JS, and maybe we can get the other areas of integration done in pure JS first and then re-visit this someday, but I thought it was an idea worth throwing out there.

**Comment by wdoug** [comment]
Yes adding more infrastructure for templating would be great! I think we
may want to have a discussion at some point around frameworks, but
handlebars sounds great for now.
